In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

digits = load_digits()

In [2]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
logistic_model.score(X_test, y_test) * 100

/home/eben-success/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


95.92592592592592

In [4]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test) * 100

99.44444444444444

In [5]:
random = RandomForestClassifier()
random.fit(X_train, y_train)
random.score(X_test, y_test) * 100

98.14814814814815

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train) 
    return model.score(X_test, y_test)

In [15]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

/home/eben-success/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [18]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [20]:
scores_l  = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = train_test_split(digits.data [train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]) 
    print(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    print(get_score(SVC(), X_train, X_test, y_train, y_test))
    print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    
    

ValueError: Found input variables with inconsistent numbers of samples: [1198, 599, 1198, 599]